### ISSUE TITLE
P2p code review

### ISSUE THREAD

**Issue by nyatindopatrick** [nyatindopatrick/enumerable-module#2]
Please leave some comments

**Comment by patriciachrysy** [comment]
Perfect for me, nothing to say!!! Good job @nyatindopatrick

**Comment by dili021** [comment]
Nice to see this project done a bit differently. Good work!

**Comment by Kyle-Law** [comment]
`p [].my_none?` should return True rather than False.

Apart from that, everything looks great :)

**Comment by nyatindopatrick** [comment]
Thanks for the comments.
